version: "3"
services:
  proxy:
    image: nginx:latest   # 최신 버전의 Nginx 사용
    container_name: proxy # container 이름은 proxy
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf # nginx 설정 파일 volume 맵핑
      - ./nginx/conf.d/app.conf:/etc/nginx/app.conf # nginx 설정 파일 volume 맵핑
    depends_on:
      - springboot
  springboot:
    build:
      context: ./ # 빌드할 Dockerfile이 위치한 경로
    container_name: springboot
    expose:
      - 8080